#!/usr/bin/env python3
"""
Temporal evolution of polarization Va(t) for Vicsek simulations.

Reads run folders generated by the Java simulation:
- trajectory.txt (t id x y vx vy theta)
- properties.txt (key=value)

Main goal: help choose the averaging window in the stationary state.

Examples:
- python visualization/plot_va_time.py --run-dir simulation/outputs/run_20260324_101010_123
- python visualization/plot_va_time.py --outputs-dir simulation/outputs --latest-count 3
- python visualization/plot_va_time.py --outputs-dir simulation/outputs --latest-count 3 --save visualization/va_time.png
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot temporal evolution of polarization Va(t).")
    parser.add_argument(
        "--run-dir",
        type=Path,
        action="append",
        default=[],
        help="Path to one run directory. Repeat this argument to include multiple runs.",
    )
    parser.add_argument(
        "--outputs-dir",
        type=Path,
        default=None,
        help="Path to outputs directory containing run_* folders.",
    )
    parser.add_argument(
        "--latest-count",
        type=int,
        default=0,
        help="Include the N most recent runs from outputs-dir.",
    )
    parser.add_argument(
        "--tail-fraction",
        type=float,
        default=0.25,
        help="Fraction of final trajectory used as stationary reference mean.",
    )
    parser.add_argument(
        "--tolerance",
        type=float,
        default=0.1,
        help="Tolerance band around tail mean used to detect stationarity.",
    )
    parser.add_argument(
        "--stay-steps",
        type=int,
        default=100,
        help="Minimum consecutive steps inside tolerance to accept stationary start.",
    )
    parser.add_argument(
        "--min-step",
        type=int,
        default=100,
        help="Do not detect stationarity before this step.",
    )
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
        help="Optional output image path (png, pdf, svg). If omitted, opens interactive window.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=140,
        help="DPI used when saving figure.",
    )
    return parser.parse_args()


def parse_properties(path: Path) -> Dict[str, str]:
    props: Dict[str, str] = {}
    if not path.exists():
        return props

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        props[k.strip()] = v.strip()
    return props


def as_float(props: Dict[str, str], key: str, default: float) -> float:
    value = props.get(key)
    if value is None:
        return default
    try:
        return float(value)
    except ValueError:
        return default


def as_int(props: Dict[str, str], key: str, default: int) -> int:
    value = props.get(key)
    if value is None:
        return default
    try:
        return int(float(value))
    except ValueError:
        return default


def detect_stationary_start(
    va_series: np.ndarray,
    min_step: int,
    tail_fraction: float,
    tolerance: float,
    stay_steps: int,
) -> Optional[int]:
    n_steps = len(va_series)
    if n_steps == 0:
        return None

    tail_fraction = float(np.clip(tail_fraction, 0.05, 0.95))
    tail_start = max(int((1.0 - tail_fraction) * n_steps), 0)
    tail_mean = float(np.mean(va_series[tail_start:]))

    begin = int(np.clip(min_step, 0, n_steps - 1))
    stay = max(int(stay_steps), 1)

    for t0 in range(begin, max(begin, n_steps - stay + 1)):
        segment = va_series[t0 : t0 + stay]
        if len(segment) < stay:
            break
        if np.all(np.abs(segment - tail_mean) <= tolerance):
            return t0
    return None


def parse_trajectory(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Missing trajectory file: {path}")

    data = np.loadtxt(path, skiprows=1)
    if data.ndim == 1:
        data = data.reshape(1, -1)
    if data.shape[1] != 7:
        raise ValueError(f"Expected 7 columns in trajectory, got {data.shape[1]} at {path}")
    return data


def compute_va_t(data: np.ndarray, props: Dict[str, str]) -> Tuple[np.ndarray, np.ndarray]:
    t = data[:, 0].astype(np.int64)
    vx = data[:, 4]
    vy = data[:, 5]

    n_steps = int(t.max()) + 1
    n_by_t = np.bincount(t, minlength=n_steps)

    sum_vx = np.bincount(t, weights=vx, minlength=n_steps)
    sum_vy = np.bincount(t, weights=vy, minlength=n_steps)

    n_from_props = as_int(props, "N", 0)
    n_particles = n_from_props if n_from_props > 0 else int(np.max(n_by_t))

    v0_from_props = as_float(props, "v0", -1.0)
    if v0_from_props > 0:
        denom = n_particles * v0_from_props
        va = np.sqrt(sum_vx * sum_vx + sum_vy * sum_vy) / denom
    else:
        speed = np.sqrt(vx * vx + vy * vy)
        sum_speed = np.bincount(t, weights=speed, minlength=n_steps)
        denom = np.where(sum_speed > 0.0, sum_speed, 1.0)
        va = np.sqrt(sum_vx * sum_vx + sum_vy * sum_vy) / denom

    t_axis = np.arange(n_steps, dtype=np.int64)
    return t_axis, va


def default_outputs_dir() -> Path:
    candidates = [Path("simulation") / "outputs", Path("outputs")]
    for c in candidates:
        if c.exists() and c.is_dir():
            return c
    return candidates[0]


def latest_runs(outputs_dir: Path, count: int) -> List[Path]:
    if count <= 0:
        return []
    if not outputs_dir.exists() or not outputs_dir.is_dir():
        raise FileNotFoundError(f"outputs-dir does not exist: {outputs_dir}")

    run_dirs = []
    for trajectory in outputs_dir.rglob("trajectory.txt"):
        run_dir = trajectory.parent
        if (run_dir / "properties.txt").exists():
            run_dirs.append(run_dir)

    run_dirs.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return run_dirs[:count]


def resolve_run_dirs(args: argparse.Namespace) -> List[Path]:
    run_dirs = list(args.run_dir)
    if args.latest_count > 0:
        outputs = args.outputs_dir if args.outputs_dir is not None else default_outputs_dir()
        run_dirs.extend(latest_runs(outputs, args.latest_count))

    unique: List[Path] = []
    seen = set()
    for p in run_dirs:
        rp = p.resolve()
        if rp not in seen:
            seen.add(rp)
            unique.append(rp)

    if not unique:
        outputs = args.outputs_dir if args.outputs_dir is not None else default_outputs_dir()
        auto = latest_runs(outputs, 1)
        if not auto:
            raise ValueError("No run directories found. Use --run-dir or --outputs-dir --latest-count.")
        unique = auto

    return unique


def main() -> None:
    args = parse_args()

    if args.latest_count < 0:
        raise ValueError("--latest-count must be >= 0")
    if not (0.0 < args.tail_fraction < 1.0):
        raise ValueError("--tail-fraction must be in (0, 1)")
    if args.tolerance <= 0:
        raise ValueError("--tolerance must be > 0")

    run_dirs = resolve_run_dirs(args)
    n_plots = len(run_dirs)

    fig, axes = plt.subplots(n_plots, 1, figsize=(10.0, 3.2 * n_plots), squeeze=False, sharex=False)

    for idx, run_dir in enumerate(run_dirs):
        ax = axes[idx, 0]

        trajectory_path = run_dir / "trajectory.txt"
        properties_path = run_dir / "properties.txt"

        props = parse_properties(properties_path)
        data = parse_trajectory(trajectory_path)
        t_axis, va = compute_va_t(data, props)

        t_stationary = detect_stationary_start(
            va_series=va,
            min_step=args.min_step,
            tail_fraction=args.tail_fraction,
            tolerance=args.tolerance,
            stay_steps=args.stay_steps,
        )

        ax.plot(t_axis, va, color="#1f77b4", linewidth=1.6, alpha=0.95, label="Va(t)")

        if t_stationary is not None:
            ax.axvline(t_stationary, color="#d62728", linestyle="--", linewidth=1.5, label=f"stationary start ~ {t_stationary}")
            ax.axvspan(t_stationary, t_axis[-1], color="#d62728", alpha=0.08)

        eta = props.get("eta", "?")
        rho = props.get("density", "?")
        n_particles = props.get("N", "?")
        scenario = props.get("scenario", props.get("model", "?"))
        run_name = run_dir.name

        ax.set_title(f"{run_name} | scenario={scenario}, eta={eta}, density={rho}, N={n_particles}")
        ax.set_xlabel("time step t")
        ax.set_ylabel("Va")
        ax.set_ylim(0.0, 1.02)
        ax.grid(alpha=0.25)
        ax.legend(loc="best", fontsize=8)

    fig.suptitle("Temporal Evolution of Polarization Va(t)", fontsize=13)
    fig.tight_layout(rect=[0.0, 0.0, 1.0, 0.98])

    if args.save is not None:
        args.save.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.save, dpi=args.dpi)
        print(f"Saved figure: {args.save.resolve()}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
